library(dplyr)
library(here)

calculate_group_standings <- function(csv_file) {
  cat(sprintf("📊 Reading match data from %s...\n", csv_file))
  
  if (!file.exists(csv_file)) {
    stop(sprintf("❌ Error: Could not find %s. Please run fetch_fixtures.R first!", csv_file))
  }
  
  # Read the clean CSV generated by our R fetch script
  parsed_df <- read.csv(csv_file, stringsAsFactors = FALSE)
  
  # Remove the 'games.' prefix from all column names generated by jsonlite
  names(parsed_df) <- gsub("^games\\.", "", names(parsed_df))
  
  # Filter for only group stage matches that are finished
  # Note: The API might return strings like "TRUE" or booleans depending on the dump
  parsed_df <- parsed_df %>%
    filter(type == "group" & (finished == "TRUE" | finished == TRUE))
  
  if (nrow(parsed_df) == 0) {
    stop("⚠️ No finished group stage matches found to calculate.")
  }
  
  # Calculate stats for Home teams
  home_stats <- parsed_df %>%
    select(Group = group, Team = home_team_name_en, GF = home_score, GA = away_score) %>%
    mutate(
      GF = as.numeric(GF),
      GA = as.numeric(GA),
      Points = case_when(GF > GA ~ 3, GF == GA ~ 1, TRUE ~ 0)
    )
  
  # Calculate stats for Away teams
  away_stats <- parsed_df %>%
    select(Group = group, Team = away_team_name_en, GF = away_score, GA = home_score) %>%
    mutate(
      GF = as.numeric(GF),
      GA = as.numeric(GA),
      Points = case_when(GF > GA ~ 3, GF == GA ~ 1, TRUE ~ 0)
    )
  
  # Combine both home and away into a single table
  all_stats <- bind_rows(home_stats, away_stats)
  
  # Group by Team and aggregate to build the final standings table
  standings <- all_stats %>%
    group_by(Group, Team) %>%
    summarise(
      Played = n(),
      Points = sum(Points),
      GF = sum(GF),
      GA = sum(GA),
      GD = sum(GF) - sum(GA),
      .groups = 'drop'
    ) %>%
    # Sort by Group (A-Z), then Points (High-Low), GD (High-Low), GF (High-Low)
    arrange(Group, desc(Points), desc(GD), desc(GF))
  
  # Print the standings nicely formatted to the console
  cat("\n🏆 CURRENT GROUP STANDINGS 🏆\n")
  cat(paste0(rep("=", 40), collapse = ""), "\n")
  
  # Split by group and print
  groups <- unique(standings$Group)
  for (g in groups) {
    cat(sprintf("\n🌍 GROUP %s\n", g))
    group_table <- standings %>% filter(Group == g) %>% select(-Group)
    print(as.data.frame(group_table), row.names = TRUE)
  }
  
  # Export to CSV
  output_file <- here("data", "group_standings_R.csv")
  write.csv(standings, output_file, row.names = FALSE)
  cat(sprintf("\n✅ Standings successfully calculated in R and exported to: %s\n", output_file))
}

# Run the function using the new clean CSV
calculate_group_standings(here("data", "clean_fixtures.csv"))
